test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

microsoft:
  service: AzureStorage
  storage_account_name: <%= ENV["AZURE_IMAGE_STORAGE_ACCOUNT"] %>
  storage_access_key: <%= ENV["AZURE_IMAGE_STORAGE_ACCESS_KEY"] %>
  container: <%= ENV["AZURE_IMAGE_CONTAINER_NAME"] %>

